Update git-secrets.yml

diff --git a/.github/workflows/git-secrets.yml b/.github/workflows/git-secrets.yml
--- a/.github/workflows/git-secrets.yml
+++ b/.github/workflows/git-secrets.yml
@@ -1,34 +1,34 @@
-name: Reusable Git Secrets Scan
+# name: Reusable Git Secrets Scan
 
-on:
-  pull_request:
-  push:
-    branches:
-      - main
-      - develop
+# on:
+#   pull_request:
+#   push:
+#     branches:
+#       - main
+#       - develop
   
-jobs:
-    secret-scan:
-        runs-on: windows-latest
-        steps:
-            - name: Checkout Repository
-              uses: actions/checkout@v3
+# jobs:
+#     secret-scan:
+#         runs-on: windows-latest
+#         steps:
+#             - name: Checkout Repository
+#               uses: actions/checkout@v3
 
-            - name: Set Execution Policy for PowerShell
-              run: Set-ExecutionPolicy Bypass -Scope Process -Force
+#             - name: Set Execution Policy for PowerShell
+#               run: Set-ExecutionPolicy Bypass -Scope Process -Force
 
-            - name: Run Powershell Instalation Script
-              run: scripts/script.ps1
+#             - name: Run Powershell Instalation Script
+#               run: scripts/script.ps1
 
-            - name: Scan for secrets
-              run: |
-                git secrets --scan
-              continue-on-error: false
+#             - name: Scan for secrets
+#               run: |
+#                 git secrets --scan
+#               continue-on-error: false
 
-            - name: Fail if Secrets Are Found
-              run: |
-                if ($LASTEXITCODE -ne 0) {
-                    Write-Host "Error: secrets detected"
-                    exit 1
-                    }
+#             - name: Fail if Secrets Are Found
+#               run: |
+#                 if ($LASTEXITCODE -ne 0) {
+#                     Write-Host "Error: secrets detected"
+#                     exit 1
+#                     }
 
